import fs from 'fs'
import path from 'path'
import type { TypologyViewerManifest } from '@/components/coin-types/TypologyViewer'

/**
 * Generated by scripts/gen-coin-hierarchy-diagram.py (rerun it whenever
 * public/images/type_imgs gets new photos or coin_type_hierarchy changes) --
 * read once here, server-side, wherever a page needs to hand TypologyViewer
 * its manifest prop (app/coin-types/page.tsx, app/page.tsx).
 */
export function loadTypologyManifest(): TypologyViewerManifest {
  const raw = fs.readFileSync(path.join(process.cwd(), 'public/data/coin-type-hierarchy.json'), 'utf8')
  return JSON.parse(raw)
}
